apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: led-monitoring
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes
    repoURL: https://github.com/sentairanger/Youtube-Cloud-Native
    targetRevision: HEAD
  syncPolicy: {}